"""add is_admin to user

Revision ID: 4622d8aafe0f
Revises: a2bcaf338982
Create Date: 2025-08-15 19:48:27.684779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4622d8aafe0f'
down_revision = 'a2bcaf338982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_post_like', ['user_id', 'post_id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_post_like', type_='unique')

    # ### end Alembic commands ###
